# DataSource Config
#代表线上环境所使用的的config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/myeasyblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678

shiro-redis:
  enabled: true
  redis-manager:
    host: redis:6379